//
// File generated by rootcint at Sat Jan 24 10:48:27 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NPDGCutSetterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NPDGCutSetterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void NPDGRunFile_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_NPDGRunFile(void *p);
   static void deleteArray_NPDGRunFile(void *p);
   static void destruct_NPDGRunFile(void *p);
   static void streamer_NPDGRunFile(TBuffer &buf, void *obj);
   static void reset_NPDGRunFile(void *obj, TFileMergeInfo *info);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::NPDGRunFile*)
   {
      ::NPDGRunFile *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NPDGRunFile >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NPDGRunFile", ::NPDGRunFile::Class_Version(), "./NPDGRunFile.h", 36,
                  typeid(::NPDGRunFile), DefineBehavior(ptr, ptr),
                  &::NPDGRunFile::Dictionary, isa_proxy, 0,
                  sizeof(::NPDGRunFile) );
      instance.SetDelete(&delete_NPDGRunFile);
      instance.SetDeleteArray(&deleteArray_NPDGRunFile);
      instance.SetDestructor(&destruct_NPDGRunFile);
      instance.SetStreamerFunc(&streamer_NPDGRunFile);
      instance.SetResetAfterMerge(&reset_NPDGRunFile);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::NPDGRunFile*)
   {
      return GenerateInitInstanceLocal((::NPDGRunFile*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NPDGRunFile*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void NPDGCutSetter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void NPDGCutSetter_Dictionary();
   static void delete_NPDGCutSetter(void *p);
   static void deleteArray_NPDGCutSetter(void *p);
   static void destruct_NPDGCutSetter(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::NPDGCutSetter*)
   {
      ::NPDGCutSetter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::NPDGCutSetter),0);
      static ::ROOT::TGenericClassInfo 
         instance("NPDGCutSetter", "./NPDGCutSetter.h", 69,
                  typeid(::NPDGCutSetter), DefineBehavior(ptr, ptr),
                  0, &NPDGCutSetter_Dictionary, isa_proxy, 0,
                  sizeof(::NPDGCutSetter) );
      instance.SetDelete(&delete_NPDGCutSetter);
      instance.SetDeleteArray(&deleteArray_NPDGCutSetter);
      instance.SetDestructor(&destruct_NPDGCutSetter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::NPDGCutSetter*)
   {
      return GenerateInitInstanceLocal((::NPDGCutSetter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NPDGCutSetter*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void NPDGCutSetter_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::NPDGCutSetter*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
TClass *NPDGRunFile::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *NPDGRunFile::Class_Name()
{
   return "NPDGRunFile";
}

//______________________________________________________________________________
const char *NPDGRunFile::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::NPDGRunFile*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NPDGRunFile::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::NPDGRunFile*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NPDGRunFile::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::NPDGRunFile*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NPDGRunFile::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::NPDGRunFile*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void NPDGRunFile::Streamer(TBuffer &R__b)
{
   // Stream an object of class NPDGRunFile.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TFile::Streamer(R__b);
      R__b >> allCutsDefined_;
      R__b >> tTree_;
      R__b >> tgCut_;
      R__b >> tdcGamma0_;
      R__b >> tdcLow_;
      R__b >> tdcHigh_;
      R__b >> ndLongLow_;
      R__b >> ndLongHigh_;
      R__b >> bg1Low_;
      R__b >> bg1High_;
      R__b >> bg2Low_;
      R__b >> bg2High_;
      R__b.CheckByteCount(R__s, R__c, NPDGRunFile::IsA());
   } else {
      R__c = R__b.WriteVersion(NPDGRunFile::IsA(), kTRUE);
      TFile::Streamer(R__b);
      R__b << allCutsDefined_;
      R__b << tTree_;
      R__b << tgCut_;
      R__b << tdcGamma0_;
      R__b << tdcLow_;
      R__b << tdcHigh_;
      R__b << ndLongLow_;
      R__b << ndLongHigh_;
      R__b << bg1Low_;
      R__b << bg1High_;
      R__b << bg2Low_;
      R__b << bg2High_;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void NPDGRunFile::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NPDGRunFile.
      TClass *R__cl = ::NPDGRunFile::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "allCutsDefined_", &allCutsDefined_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tTree_", &tTree_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*tgCut_", &tgCut_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdcGamma0_", &tdcGamma0_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdcLow_", &tdcLow_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdcHigh_", &tdcHigh_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ndLongLow_", &ndLongLow_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ndLongHigh_", &ndLongHigh_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bg1Low_", &bg1Low_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bg1High_", &bg1High_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bg2Low_", &bg2Low_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bg2High_", &bg2High_);
      TFile::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_NPDGRunFile(void *p) {
      delete ((::NPDGRunFile*)p);
   }
   static void deleteArray_NPDGRunFile(void *p) {
      delete [] ((::NPDGRunFile*)p);
   }
   static void destruct_NPDGRunFile(void *p) {
      typedef ::NPDGRunFile current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_NPDGRunFile(TBuffer &buf, void *obj) {
      ((::NPDGRunFile*)obj)->::NPDGRunFile::Streamer(buf);
   }
   // Wrapper around the Reset function.
   static void reset_NPDGRunFile(void *obj,TFileMergeInfo *info) {
      ((::NPDGRunFile*)obj)->ResetAfterMerge(info);
   }
} // end of namespace ROOT for class ::NPDGRunFile

namespace ROOT {
   // Wrapper around operator delete
   static void delete_NPDGCutSetter(void *p) {
      delete ((::NPDGCutSetter*)p);
   }
   static void deleteArray_NPDGCutSetter(void *p) {
      delete [] ((::NPDGCutSetter*)p);
   }
   static void destruct_NPDGCutSetter(void *p) {
      typedef ::NPDGCutSetter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::NPDGCutSetter

/********************************************************
* NPDGCutSetterDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNPDGCutSetterDict();

extern "C" void G__set_cpp_environmentNPDGCutSetterDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NPDGCutSetter.h");
  G__add_compiledheader("NPDGRunFile.h");
  G__add_compiledheader("NPDGDefine.h");
  G__cpp_reset_tagtableNPDGCutSetterDict();
}
#include <new>
extern "C" int G__cpp_dllrevNPDGCutSetterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NPDGRunFile */
static int G__NPDGCutSetterDict_541_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NPDGRunFile::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NPDGRunFile::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NPDGRunFile::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NPDGRunFile::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGRunFile*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NPDGRunFile::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NPDGRunFile::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NPDGRunFile::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NPDGRunFile::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NPDGRunFile* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NPDGRunFile(
(const char*) G__int(libp->para[0]), (Option_t*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) NPDGRunFile(
(const char*) G__int(libp->para[0]), (Option_t*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NPDGRunFile(
(const char*) G__int(libp->para[0]), (Option_t*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) NPDGRunFile(
(const char*) G__int(libp->para[0]), (Option_t*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NPDGRunFile((const char*) G__int(libp->para[0]), (Option_t*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) NPDGRunFile((const char*) G__int(libp->para[0]), (Option_t*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NPDGRunFile((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) NPDGRunFile((const char*) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NPDGRunFile* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new NPDGRunFile(*(NPDGRunFile*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) NPDGRunFile(*(NPDGRunFile*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((NPDGRunFile*) G__getstructoffset())->AllCutsDefined());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((NPDGRunFile*) G__getstructoffset())->getTree());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const NPDGRunFile& obj = ((NPDGRunFile*) G__getstructoffset())->operator=(*(NPDGRunFile*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_541_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGRunFile*) G__getstructoffset())->SaveCuts();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NPDGRunFile G__TNPDGRunFile;
static int G__NPDGCutSetterDict_541_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NPDGRunFile*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NPDGRunFile*) (soff+(sizeof(NPDGRunFile)*i)))->~G__TNPDGRunFile();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NPDGRunFile*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NPDGRunFile*) (soff))->~G__TNPDGRunFile();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* NPDGCutSetter */
static int G__NPDGCutSetterDict_710_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const NPDGCutSetter*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((NPDGCutSetter*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((NPDGCutSetter*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((NPDGCutSetter*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((NPDGCutSetter*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((NPDGCutSetter*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((NPDGCutSetter*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((NPDGCutSetter*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((NPDGCutSetter*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((NPDGCutSetter*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((NPDGCutSetter*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NPDGCutSetter* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new NPDGCutSetter(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (bool) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) NPDGCutSetter(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (bool) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NPDGCutSetter* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new NPDGCutSetter(*(NPDGCutSetter*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) NPDGCutSetter(*(NPDGCutSetter*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const NPDGCutSetter& obj = ((NPDGCutSetter*) G__getstructoffset())->operator=(*(NPDGCutSetter*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->OnHandleMenu((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->OnBackgroundRangeSet();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->OnSaveCuts();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->OnDrawHistograms();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NPDGCutSetterDict_710_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NPDGCutSetter*) G__getstructoffset())->OnCloseMainWindow();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NPDGCutSetter G__TNPDGCutSetter;
static int G__NPDGCutSetterDict_710_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NPDGCutSetter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NPDGCutSetter*) (soff+(sizeof(NPDGCutSetter)*i)))->~G__TNPDGCutSetter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NPDGCutSetter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NPDGCutSetter*) (soff))->~G__TNPDGCutSetter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NPDGRunFile */

/* NPDGCutSetter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNPDGCutSetterDict {
 public:
  G__Sizep2memfuncNPDGCutSetterDict(): p(&G__Sizep2memfuncNPDGCutSetterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNPDGCutSetterDict::*p)();
};

size_t G__get_sizep2memfuncNPDGCutSetterDict()
{
  G__Sizep2memfuncNPDGCutSetterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNPDGCutSetterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile))) {
     NPDGRunFile *G__Lderived;
     G__Lderived=(NPDGRunFile*)0x1000;
     {
       TFile *G__Lpbase=(TFile*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile),G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TFile),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TDirectoryFile *G__Lpbase=(TDirectoryFile*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile),G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TDirectoryFile),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TDirectory *G__Lpbase=(TDirectory*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile),G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TDirectory),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile),G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile),G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNPDGCutSetterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NPDGRunFile */
static void G__setup_memvarNPDGRunFile(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile));
   { NPDGRunFile *p; p=(NPDGRunFile*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"allCutsDefined_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TTree),-1,-1,4,"tTree_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TCutG),-1,-1,4,"tgCut_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"tdcGamma0_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"tdcLow_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"tdcHigh_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"ndLongLow_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"ndLongHigh_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"bg1Low_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"bg1High_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"bg2Low_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"bg2High_=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* NPDGCutSetter */
static void G__setup_memvarNPDGCutSetter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter));
   { NPDGCutSetter *p; p=(NPDGCutSetter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"isVerboseMode_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile),-1,-1,4,"runFile_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGMainFrame),-1,-1,4,"fMain_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGPopupMenu),-1,-1,4,"fMenuFile_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGStatusBar),-1,-1,4,"fStatusBar_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGHProgressBar),-1,-1,4,"fHProg_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGHorizontalFrame),-1,-1,4,"hfOptions_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGVerticalFrame),-1,-1,4,"hfOptions0_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGHorizontalFrame),-1,-1,4,"hfOptions1_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGHorizontalFrame),-1,-1,4,"hfOptions2_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGComboBox),-1,-1,4,"cbAT_=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TGComboBox),-1,-1,4,"cbBGO_=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TCut),-1,-1,4,"tcAll_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nAt_=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nBgo_=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNPDGCutSetterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNPDGRunFile(void) {
   /* NPDGRunFile */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile));
   G__memfunc_setup("Class",502,G__NPDGCutSetterDict_541_0_1, 85, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NPDGRunFile::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__NPDGCutSetterDict_541_0_2, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NPDGRunFile::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__NPDGCutSetterDict_541_0_3, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NPDGRunFile::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__NPDGCutSetterDict_541_0_4, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NPDGRunFile::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NPDGCutSetterDict_541_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NPDGCutSetterDict_541_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NPDGRunFile::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NPDGCutSetterDict_541_0_10, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NPDGRunFile::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__NPDGCutSetterDict_541_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NPDGRunFile::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NPDGCutSetterDict_541_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NPDGRunFile::DeclFileLine) ), 0);
   G__memfunc_setup("NPDGRunFile",990,G__NPDGCutSetterDict_541_0_13, 105, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile), -1, 0, 4, 1, 1, 0, 
"C - - 10 - fname C - 'Option_t' 10 '\"\"' option "
"C - - 10 '\"\"' ftitle i - 'Int_t' 0 '1' compress", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NPDGRunFile",990,G__NPDGCutSetterDict_541_0_14, 105, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile), -1, 0, 1, 1, 1, 0, "u 'NPDGRunFile' - 11 - other", "copy constructor */", (void*) NULL, 0);
   G__memfunc_setup("AllCutsDefined",1383,G__NPDGCutSetterDict_541_0_15, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTree",720,G__NPDGCutSetterDict_541_0_16, 85, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TTree), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__NPDGCutSetterDict_541_0_17, 117, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGRunFile), -1, 1, 1, 1, 1, 0, "u 'NPDGRunFile' - 11 - other", "assignment operator */", (void*) NULL, 0);
   G__memfunc_setup("SaveCuts",814,G__NPDGCutSetterDict_541_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ResetCuts",930,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadAllCuts",1076,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NPDGRunFile", 1116, G__NPDGCutSetterDict_541_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncNPDGCutSetter(void) {
   /* NPDGCutSetter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter));
   G__memfunc_setup("GetListOfSignals",1602,G__NPDGCutSetterDict_710_0_1, 85, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__NPDGCutSetterDict_710_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__NPDGCutSetterDict_710_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__NPDGCutSetterDict_710_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__NPDGCutSetterDict_710_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__NPDGCutSetterDict_710_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__NPDGCutSetterDict_710_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__NPDGCutSetterDict_710_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__NPDGCutSetterDict_710_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__NPDGCutSetterDict_710_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NPDGCutSetter",1228,G__NPDGCutSetterDict_710_0_26, 105, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter), -1, 0, 4, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h g - - 0 - vMode", "constructor      */", (void*) NULL, 0);
   G__memfunc_setup("NPDGCutSetter",1228,G__NPDGCutSetterDict_710_0_27, 105, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter), -1, 0, 1, 1, 1, 0, "u 'NPDGCutSetter' - 11 - other", "copy constructor */", (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__NPDGCutSetterDict_710_0_28, 117, G__get_linked_tagnum(&G__NPDGCutSetterDictLN_NPDGCutSetter), -1, 1, 1, 1, 1, 0, "u 'NPDGCutSetter' - 11 - other", "assignment operator */", (void*) NULL, 0);
   G__memfunc_setup("OnHandleMenu",1182,G__NPDGCutSetterDict_710_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnBackgroundRangeSet",2006,G__NPDGCutSetterDict_710_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnSaveCuts",1003,G__NPDGCutSetterDict_710_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnDrawHistograms",1644,G__NPDGCutSetterDict_710_0_32, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnCloseMainWindow",1712,G__NPDGCutSetterDict_710_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitMainFrame",1284,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OnOpenFile",975,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "C - - 10 - fname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawBackgroundLine",1814,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'TH1F' - 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetATId",610,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'TString' - 1 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBGOId",677,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'TString' - 1 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateCuts",1026,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawPad1",724,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawPad2",725,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawPad3",726,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawPad4",727,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawPad5",728,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawPad6",729,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NPDGCutSetter", 1354, G__NPDGCutSetterDict_710_0_46, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNPDGCutSetterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNPDGCutSetterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNPDGCutSetterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NPDGCutSetterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TDirectory = { "TDirectory" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TDirectoryFile = { "TDirectoryFile" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TCut = { "TCut" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TCutG = { "TCutG" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_NPDGRunFile = { "NPDGRunFile" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGHProgressBar = { "TGHProgressBar" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__NPDGCutSetterDictLN_NPDGCutSetter = { "NPDGCutSetter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNPDGCutSetterDict() {
  G__NPDGCutSetterDictLN_TClass.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TBuffer.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TDirectory.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TMemberInspector.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TObject.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TNamed.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TString.tagnum = -1 ;
  G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TList.tagnum = -1 ;
  G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TH1F.tagnum = -1 ;
  G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TFile.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TDirectoryFile.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TTree.tagnum = -1 ;
  G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TCut.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TCutG.tagnum = -1 ;
  G__NPDGCutSetterDictLN_NPDGRunFile.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TQObjSender.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGWindow.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGVerticalFrame.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGHorizontalFrame.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGMainFrame.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGPopupMenu.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGStatusBar.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGHProgressBar.tagnum = -1 ;
  G__NPDGCutSetterDictLN_TGComboBox.tagnum = -1 ;
  G__NPDGCutSetterDictLN_NPDGCutSetter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNPDGCutSetterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TDirectory);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TString);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TList);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TDirectoryFile);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TCut);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TCutG);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_NPDGRunFile),sizeof(NPDGRunFile),-1,65024,(char*)NULL,G__setup_memvarNPDGRunFile,G__setup_memfuncNPDGRunFile);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGPopupMenu);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGHProgressBar);
   G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_TGComboBox);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NPDGCutSetterDictLN_NPDGCutSetter),sizeof(NPDGCutSetter),-1,36352,(char*)NULL,G__setup_memvarNPDGCutSetter,G__setup_memfuncNPDGCutSetter);
}
extern "C" void G__cpp_setupNPDGCutSetterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNPDGCutSetterDict()");
  G__set_cpp_environmentNPDGCutSetterDict();
  G__cpp_setup_tagtableNPDGCutSetterDict();

  G__cpp_setup_inheritanceNPDGCutSetterDict();

  G__cpp_setup_typetableNPDGCutSetterDict();

  G__cpp_setup_memvarNPDGCutSetterDict();

  G__cpp_setup_memfuncNPDGCutSetterDict();
  G__cpp_setup_globalNPDGCutSetterDict();
  G__cpp_setup_funcNPDGCutSetterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNPDGCutSetterDict();
  return;
}
class G__cpp_setup_initNPDGCutSetterDict {
  public:
    G__cpp_setup_initNPDGCutSetterDict() { G__add_setup_func("NPDGCutSetterDict",(G__incsetup)(&G__cpp_setupNPDGCutSetterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNPDGCutSetterDict() { G__remove_setup_func("NPDGCutSetterDict"); }
};
G__cpp_setup_initNPDGCutSetterDict G__cpp_setup_initializerNPDGCutSetterDict;

