/********************************************************************
* NPDGCutSetterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NPDGCutSetterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNPDGCutSetterDict();
extern void G__cpp_setup_inheritanceNPDGCutSetterDict();
extern void G__cpp_setup_typetableNPDGCutSetterDict();
extern void G__cpp_setup_memvarNPDGCutSetterDict();
extern void G__cpp_setup_globalNPDGCutSetterDict();
extern void G__cpp_setup_memfuncNPDGCutSetterDict();
extern void G__cpp_setup_funcNPDGCutSetterDict();
extern void G__set_cpp_environmentNPDGCutSetterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NPDGCutSetter.h"
#include "NPDGRunFile.h"
#include "NPDGDefine.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NPDGCutSetterDictLN_TClass;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TBuffer;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TDirectory;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TMemberInspector;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TObject;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TNamed;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TString;
extern G__linked_taginfo G__NPDGCutSetterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TList;
extern G__linked_taginfo G__NPDGCutSetterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TH1F;
extern G__linked_taginfo G__NPDGCutSetterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TFile;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TDirectoryFile;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TTree;
extern G__linked_taginfo G__NPDGCutSetterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TCut;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TCutG;
extern G__linked_taginfo G__NPDGCutSetterDictLN_NPDGRunFile;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TQObjSender;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGWindow;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGVerticalFrame;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGMainFrame;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGPopupMenu;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGStatusBar;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGHProgressBar;
extern G__linked_taginfo G__NPDGCutSetterDictLN_TGComboBox;
extern G__linked_taginfo G__NPDGCutSetterDictLN_NPDGCutSetter;

/* STUB derived class for protected member access */
